name: Dump Secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Dump Secret
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: SSH - dump the secret
        uses: fifsky/ssh-action@master
        with:
          command: |
            cat << EOF > ${{ secrets.REMOTE_TARGET }}/ssh_key.txt
            ${{ secrets.SERVER_SSH_KEY }}
            EOF
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
